name: Deploy to EC2

on:
  push:
    branches:
      - main   # run only when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/VeeChat_RAG
            git pull origin main
          
            source venv/bin/activate
            pip install -r requirements.txt
            deactivate
          
            # Kill any existing Gunicorn process
            pkill -f gunicorn || true
          
            # Start Gunicorn completely detached from CI/CD session
            nohup setsid ~/VeeChat_RAG/venv/bin/gunicorn --workers 3 --bind 0.0.0.0:5000 live_agent:app > gunicorn.log 2>&1 < /dev/null &

